### ISSUE TITLE
YouTubeLiveChat.sendMessage method doesn't work

### ISSUE THREAD

**Issue by VikTo7W** [kusaanko/YouTubeLiveChat#10]
Trying to use sendMessage method leads to the error below:
![image](https://github.com/kusaanko/YouTubeLiveChat/assets/114958686/8e37253a-5125-4494-9c1b-20c181a75ba7)
After some further research figured out that the problem is in response from https://www.youtube.com/live_chat?continuation= in getInitialData method of YouTubeLiveChat class, which doesn't contain the needed "params" parameter as the request is somehow not authenticated while having all ids in cookie header. After intercepting the https://www.youtube.com/live_chat?continuation= request in a logged in session in browser i have got this as headers of a request being sent:
![image](https://github.com/kusaanko/YouTubeLiveChat/assets/114958686/ad1f09ef-8625-41a4-a9ef-4fa4cf3e409c)
I might be missing out on something but I cant see any of the headers added in YouTubeLiveChat.getHeader method apart from cookie header in the headers in the screenshot above. I have tried using those headers and still not getting an authenticated response. The only guess is that some cookie values are supposed to be generated uniquely.

**Comment by kusaanko** [comment]
A lot of time has been passed until the last update of this project, so I will update the whole code.
Thank you for your notification.

**Comment by kusaanko** [comment]
I found most of the code are still working properly.
This issue is caused by lack of some cookies.
We don't need X-Client-Data to use YouTube's live chat.

**Comment by kusaanko** [comment]
I uploaded new version 1.6.
This will fix the problem. Please try it.

**Comment by VikTo7W** [comment]
Thanks for replying to the issue, I didnt give any updates on it but i managed to make it work recently also by adding the whole cookie string as a header so pretty sure the new version will work. However, there is now an issue with some cookies which a being generated once in couple of minutes and are also compulsory to authenticate sendMessage request. For generating the params element of sendMessage payload I have taken the encoding logic from a different project in Typescript, whose dev reverse engineered the prams generation, but still wondering how to get the dynamically generated cookies.

**Comment by VikTo7W** [comment]
All good, the cookies only expire if the RotateCookies request is called so to make cookies not expire just need to have no active session of the account in browser
