### ISSUE TITLE
How I can check a stream a still alive?

### ISSUE THREAD

**Issue by argen666** [kusaanko/YouTubeLiveChat#8]
Hello,
Is it possible to check if a stream is still alive or already ends? 
If the stream is over, is it possible the library will get into an infinity loop processing the stream record?
Thanks

**Comment by kusaanko** [comment]
Yes, there is no function to exit loop process.
I looked into YouTube's response when the live stream was ending, but I can't find the data that the live was ended.
However, YouTube sends messages like "This live stream has ended 2 minutes ago".
This message depends on language setting, so I can't make a function that detects the message.
If you make such a function, please send a pull request!

**Comment by argen666** [comment]
I've created a pull request for you!
I've found a way to get mentioned info from the JSON generated with the following link:
https://www.youtube.com/watch?v={videoId}?hl=en&pbj=1

In addition to info about live broadcast details, the resulting JSON contains much extra information about the stream.
You can use it to add other helper functions to your library.
Thanks

**Comment by kusaanko** [comment]
oh, I haven't known the url ever. It's very useful to get any information. I will add some broadcast information using it.
I'll fix some codes and accept the pull request #9. Thanks!

**Comment by kusaanko** [comment]
Your pull request was released as version 1.5.
Thanks for your contribution.

**Comment by argen666** [comment]
Great, thank you!
